# Generated by Django 5.2.12 on 2026-04-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='course',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='img',
        ),
    ]
